### ISSUE TITLE
Will there be a file transport?

### ISSUE THREAD

**Issue by taoqf** [onubo/react-native-logs#1]
Great lib, thank you for your work.
Maybe we could use [react-native-fs](https://www.npmjs.com/package/react-native-fs), but I just found that 3.0.0 has some issues with java exceptions. So actually I don't know how could we use the `fs` module.

**Comment by alessandro-bottamedi** [comment]
Do you need to save the logs to a file in order to send it to a server in a second time? in this case we could use, in the transport, the api `appendFile` and then `uploadFiles` of `react-native-fs`. I can do tests.
As an alternative we could use async-storage to save all the logs or do you need the file?

**Comment by taoqf** [comment]
Thanks.
File, indeed.
Because I would like to see a logfile especially when the app crashed.

**Comment by samaneh-kamalian** [comment]
> Thanks.
> File, indeed.
> Because I would like to see a logfile especially when the app crashed.

I need file too.
will it add to lib?

**Comment by alessandro-bottamedi** [comment]
@samaneh-kamalian I'm working on it, soon I'll update the repository.

**Comment by samaneh-kamalian** [comment]
> @samaneh-kamalian I'm working on it, soon I'll update the repository.

thanks a lot.
so I am going to use your lib and waiting for your update :)

**Comment by alessandro-bottamedi** [comment]
@samaneh-kamalian @taoqf I finally added the new transport to save the logs to file, it requires react-native-fs. Tomorrow I will release the new version on npm, which also includes some breaking changes.

**Comment by alessandro-bottamedi** [comment]
I have bublished the new version on NPM so i close this issue.

**Comment by ajaysaini-sgvu** [comment]
@alessandro-bottamedi Do you have working sample code for writing logs into file ?

**Comment by alessandro-bottamedi** [comment]
@ajaysaini-sgvu 
simplest working sample:

1. install [react-native-fs](https://github.com/itinance/react-native-fs).
2. put this code in your app:
```
import { logger } from 'react-native-logs';
import { rnFsFileAsync } from 'react-native-logs/dist/transports/rnFsFileAsync';

const config = {
  transport: rnFsFileAsync,
  transportOptions: {
    loggerName: 'myLogsFile',
  },
};

// create logger with above config
var log = logger.createLogger(config);

log.debug('This is a debug log');
log.info('This is an info log');
log.warn('This is a warning  log');
log.error('This is an error log');
```
3. well done, if you run the app you can find the log file "myLogsFile.txt" in the document directory of your device/simulator.

PS:
in the [Usage Tips](https://github.com/onubo/react-native-logs#usage-tips) of the readme you can find an example where a global logger is created in the config.js file, you can use that example and set the rnFsFileAsync transport as I did in the code above.
