### ISSUE TITLE
Support for common console.log multiple args

### ISSUE THREAD

**Issue by pke** [onubo/react-native-logs#10]
In browsers logger implementation one can write:

```js
const bar = "bar"
logger.log("foo", bar)
```

which will lead to one line of text output delimited by space, between each arguments `toString()` call result: `foo bar`

This library would output 2 lines of logging at the moment.
Is it to late to change that behaviour?

**Comment by alessandro-bottamedi** [comment]
Yes you are right, I am thinking how to implement multiple logs on the same line but leaving the transport logic unchanged. Maybe I can move the argument loop in the transport functions, suggestions?

**Comment by alessandro-bottamedi** [comment]
In the ver 3 i will implement a better arguments concatenation, there's still work to be done ;)
