### ISSUE TITLE
colorConsoleSync not showing colors in VSCode

### ISSUE THREAD

**Issue by objectiveSee** [onubo/react-native-logs#11]
Issue: My logs are not colored in VSCod. Instead, they show up with strings describing the colors:

output:
<img width="1142" alt="Screen Shot 2020-05-22 at 2 13 47 PM" src="https://user-images.githubusercontent.com/1684106/82709884-772fa680-9c36-11ea-8e18-2550008e5f05.png">

code:
```

const defaultConfig = {
  severity: 'debug',
  transport: colorConsoleSync,
  // transport: customTransport,
  transportOptions: null,
  levels: {
    debug: 0,
    info: 1,
    warn: 2,
    error: 3,
  },
};

const _logger = logger.createLogger(defaultConfig);
```

I also get the same output when using `consoleSync`

**Comment by alessandro-bottamedi** [comment]
i've just added `ansiColorConsoleSync` transport for this purpose, try it.

**Comment by objectiveSee** [comment]
@alessandro-bottamedi I updated to `react-native-logs@2.2.1` but still have the colors being logged out as string instead of being colored. Here's my logger config code and a sample of the logs in VSCode. Any ideas of what to try?

```
import { logger } from 'react-native-logs';
import { ansiColorConsoleSync } from 'react-native-logs/dist/transports/colorConsoleSync';

const defaultConfig = {
  severity: 'debug',
  transport: ansiColorConsoleSync,
  transportOptions: {
    hideDate: true,
    dateFormat: 'iso',
    hideLevel: true,
    loggerName: 'hitcher',
  },
  levels: {
    debug: 0,
    info: 1,
    warn: 2,
    error: 3,
  },
};

const _logger = logger.createLogger(defaultConfig);
```

**VSCode Terminal output**
<img width="806" alt="Screen Shot 2020-05-27 at 12 58 46 PM" src="https://user-images.githubusercontent.com/1684106/83066372-cfd9b780-a019-11ea-80d2-f39c02a3ce26.png">

**Comment by objectiveSee** [comment]
To clarify, my logs still end in `color: dodgerblue;font-weight:bold` which is added by this module.

**Comment by alessandro-bottamedi** [comment]
change the second Line to
`import { ansiColorConsoleSync } from 'react-native-logs/dist/transports/ansiColorConsoleSync'; `

**Comment by objectiveSee** [comment]
Ahh great catch! Thank you so much for your help @alessandro-bottamedi! 🤷‍♂️🎵
