### ISSUE TITLE
Unrecognised event output

### ISSUE THREAD

**Issue by MichaelKim39** [onubo/react-native-logs#13]
![image](https://user-images.githubusercontent.com/32578159/87218330-8b944380-c349-11ea-9ba5-e441a68669ab.png)
I seem to be getting an "unrecognised event" line being output for every log.info I do, I can not find anything online about how to solve this, do you have any advice?

**Comment by MichaelKim39** [comment]
The code spawning this issue: 
![image](https://user-images.githubusercontent.com/32578159/87218350-b2527a00-c349-11ea-8c64-7f235c6dde4a.png)
![image](https://user-images.githubusercontent.com/32578159/87218355-bbdbe200-c349-11ea-91f8-0c00aeeec3d6.png)

**Comment by alessandro-bottamedi** [comment]
Hi, this is not an error related to `react-native-logs`, can I know some information about your system? Do you use expo or is it a bare react-native app? do you use redux?

If you use EXPO try to upgrade your expo-cli: `npm install -g expo-cli` and then run your app.

**Comment by MichaelKim39** [comment]
Thank you! I realised I was using npm to update expo-cli which was not working as expected, using yarn sorted it!

**Comment by alessandro-bottamedi** [comment]
You're welcome
