### ISSUE TITLE
Global logger?

### ISSUE THREAD

**Issue by himat** [onubo/react-native-logs#14]
Hi, great library.

But instead of having to do in every file:
```
import { logger } from 'react-native-logs';

var log = logger.createLogger();
log.info('This is an Info log');
```

is there a way to do:
```
import { logger } from 'react-native-logs';

logger.info('This is an Info log');
```

It would be way simpler to just import the logger wherever I want instead of having to also create the logger in every file as well. 
For example, loguru in python does this and it's great https://github.com/Delgan/loguru#ready-to-use-out-of-the-box-without-boilerplate

**Comment by alessandro-bottamedi** [comment]
As you can see from the "[Usage Tips](https://github.com/onubo/react-native-logs#global-logger-in-react-native)" section of the documentation you can create a gobal logger as follows:

```javascript
// file config.js
import { logger } from 'react-native-logs';
import { colorConsoleAfterInteractions } from 'react-native-logs/dist/transports/colorConsoleAfterInteractions';

const config = {
  transport: colorConsoleAfterInteractions,
};
var log = logger.createLogger(config);

if (__DEV__) {
  log.setSeverity('debug');
} else {
  log.setSeverity('error');
}

export { log };
```

```javascript
// file index.js and other app files
import { log } from './config';

log.info('app log test');
```
