### ISSUE TITLE
Log rotate feature

### ISSUE THREAD

**Issue by yash-habilelabs** [onubo/react-native-logs#16]
Hi
i am using this log package, but i want to use log-rotate with this, which create new file on date change, is there any way how i can achieve.

**Comment by alessandro-bottamedi** [comment]
Yes, you can use the `loggerName` options with `rnFsFileAsync` transport and pass to it today date, so every day the log file name will change with today date:

```javascript
let today = new Date();
const config = {
  transport: rnFsFileAsync,
  transportOptions: {
    hideDate: true,
    loggerName: `logs_${today.getDate()}-${today.getMonth()+1}-${today.getFullYear()}.txt`,
  },
}; 
```

**Comment by yash-habilelabs** [comment]
Hi
thanks for the help @alessandro-bottamedi . i tried the same with hideDate: false option. it's working only when we open the app every day. not like app is continues open.

**Comment by alessandro-bottamedi** [comment]
@yash-habilelabs Hi, I did not understand the problem, do you have logs even while the application is closed? or is the date incorrect?

**Comment by gametack** [comment]
> Yes, you can use the `loggerName` option with `rnFsFileAsync` transport and pass today date to it, so every day the log file name will change with today date:
> 
> ```js
> let today = new Date();
> const config = {
>   transport: rnFsFileAsync,
>   transportOptions: {
>     hideDate: true,
>     loggerName: `logs_${today.getDate()}-${today.getMonth()+1}-${today.getFullYear()}.txt`,
>   },
> }; 
> ```
> 
> with this configuration the file name for today will be: `logs_21-7-2020.txt`

very clever. thanks!

**Comment by CDBridger** [comment]
Any chance we can rotate logs based on file size too? e.g once file size hits >50mb rotate to a new file?
