### ISSUE TITLE
Multiple arguments concatenation

### ISSUE THREAD

**Issue by dsamojlenko** [onubo/react-native-logs#20]
[In this section of the docs](https://github.com/onubo/react-native-logs#multiple-arguments) it says multiple arguments will be concatenated, but they are actually output on separate lines. 

Using the example provided, the logs look like this:
![image](https://user-images.githubusercontent.com/1187115/100280932-f92ac000-2f36-11eb-8ce8-04c8ffce4a0b.png)

Is that the intention? Or should they be concatenated on a single line?

**Comment by alessandro-bottamedi** [comment]
for now it works like this but it will be fixed in the next release, sorry for the delay...

**Comment by alessandro-bottamedi** [comment]
Fixed in v 3.0.0
