### ISSUE TITLE
Potentially redundant .then()?

### ISSUE THREAD

**Issue by chmac** [onubo/react-native-logs#21]
Saw this:

https://github.com/onubo/react-native-logs/blob/913eb01ac550970b659528ae04a80080bce85b4c/src/transports/rnFsFileAsync.ts#L45

I think the `.then()` is redundant? Or maybe it serves some purpose that's not immediately obvious to me?

**Comment by alessandro-bottamedi** [comment]
Yes I must have left it by mistake, I'll remove it in the next commit thanks
