### ISSUE TITLE
Would it make sense to remove dist from git?

### ISSUE THREAD

**Issue by chmac** [onubo/react-native-logs#23]
Would it make sense to remove the built javascript dist folder from git? I'm used to TypeScript packages that only check the src folder into git. Maybe there's something I'm missing here?

**Comment by alessandro-bottamedi** [comment]
Usually I don't include the dist folder either, but leaving it there is convenient for me to publish the package on npm

**Comment by chmac** [comment]
@alessandro-bottamedi Gotcha. Is there a risk that `dist` gets out of date from `src` that way? That is usually my concern with the approach. I tend to put build and publish scripts into `package.json` so that I'm consistent, otherwise I always end up forgetting parts of the process.

**Comment by alessandro-bottamedi** [comment]
@chmac You're right, in fact I have inserted in package.json this little script: `"precommit": "rm -rf dist && tsc && jest --verbose"` but there is the risk of forgetting to run it.

Maybe in the next version I will consider whether to delete dist folder

**Comment by alessandro-bottamedi** [comment]
Fixed in v 3.0.0
