### ISSUE TITLE
How can I save log in file manager (storage) of mobile.

### ISSUE THREAD

**Issue by Shahanshah87** [onubo/react-native-logs#24]
I want to save log file in file manager of my app. 
So that I can see my log file in File Manager->android->com.appname->pathToLogFile.txt

What I have tried till now is:-

  `  import React from 'react';
        import { logger } from 'react-native-logs';
         import { consoleSync } from 'react-native-logs/dist/transports/consoleSync';
         import { colorConsoleSync } from 'react-native-logs/dist/transports/colorConsoleSync';
         import { colorConsoleAfterInteractions } from 'react-native-logs/dist/transports/colorConsoleAfterInteractions';
         import { rnFsFileAsync } from 'react-native-logs/dist/transports/rnFsFileAsync';
  
     var customTransport = (msg, level, options) => {
      // Do here whatever you want with the log message
      // Eg. a console log: console.log(level.text, msg)
     };

     const log = logger.createLogger({
      transport: (msg, level, options) => {
          colorConsoleSync(msg, level, options);  
          rnFsFileAsync(msg, level, options);
          //customTransport(msg, level, options);
       },
       transportOptions: {
          hideDate: true,     //change to show date and time
         dateFormat: 'iso',   //change date format
         hideLevel: true,     //change to show level of debug
         loggerName: 'log',      //name of file in file manager as <loggerPath>/<fileName>.txt
       },
      });

      if (__DEV__) {
        log.setSeverity('debug');   //it will show log of debug, info, warn & error in development mode
      } else {
       log.setSeverity('warn');   //it will show log of warn & error only in production mode
     }

    export default log;
`
How can I achieve this?

**Comment by alessandro-bottamedi** [comment]
Try to change the loggerPath with ExternalStorageDirectoryPath: 

```javascript
const log = logger.createLogger({
  transport: (msg, level, options) => {
    colorConsoleSync(msg, level, options);  
    rnFsFileAsync(msg, level, options);
  },
  transportOptions: {
    hideDate: true,
    dateFormat: 'iso',
    hideLevel: true,
    loggerName: 'log.txt',
    loggerPath: RNFS.ExternalStorageDirectoryPath
  },
});
```

With this path you should see the file in the File Manager

**Comment by Shahanshah87** [comment]
It worked thank you!!!

**Comment by codemap01** [comment]
@shahanshah87 I need your help I'm not able to generate and  save log in file manager (storage) of mobile device 
 
`import { logger, fileAsyncTransport } from 'react-native-logs';

var RNFS = require('react-native-fs');
const log = logger.createLogger({
    levels: {
        debug: 1,
        info: 2,
        warn: 3,
        error: 4,
    },
    transport: fileAsyncTransport,
    transportOptions: {
        FS: RNFS,
        fileName: `testLogs.txt`,
    },
});
log.debug('This is a Debug log 1');
export const LoggerUI = () => {
    log.debug('This is a Debug log=>TEST12 ');
    log.info('This is an Info log=> TEST 23');
    log.warn('This is a Warning log=> TEST 34');
    log.error('This is an Error log=> TEST 12345678');
    return true;
};`
