### ISSUE TITLE
Error-Log-Level color is green in v 3.0.0

### ISSUE THREAD

**Issue by fuggerstadt1907** [onubo/react-native-logs#26]
Hi @alessandro-bottamedi 

thx for the new release but unfortunately error loggs are now printed in a green color which doesn't indicates an error on the first look. 

![Screenshot 2021-01-27 at 16 06 16](https://user-images.githubusercontent.com/34302057/106010337-9e8a1d80-60b9-11eb-9d0d-97038aaf156d.png)

Screenshots shows transportOptions.color:
1. null
2. ansi
3. web

**Comment by alessandro-bottamedi** [comment]
Woops, fixed in 3.0.2 ;)

**Comment by alessandro-bottamedi** [comment]
I will add the possibility to change colors for each level in next release...
