### ISSUE TITLE
Enable optional formatting / stringify

### ISSUE THREAD

**Issue by mvehar** [onubo/react-native-logs#27]
https://github.com/onubo/react-native-logs/blob/4ffa72226667ff25b643249e39c418e5a05255e6/src/index.ts#L255

In 3.0.0 transports get already stringified message. 

Add config option to disable stringify of message or add an option to provide serializer function for msg. 

I know there is rawMsg, but I have problem with JSON.stringify not handling circular dependencies.

**Comment by alessandro-bottamedi** [comment]
wouldn't adding an option to disable message stringing give the same result as rawMsg? what's the difference? you'd still have the problem of circular dependencies and JSON.stringify... 

To solve the problem try passing the rawMsg to a custom stringify function like here::
[print-a-circular-structure](https://stackoverflow.com/questions/11616630/how-can-i-print-a-circular-structure-in-a-json-like-format)

Remember that the stringified message passed to the transports also allows the concatenation of logs, so if you use multiple messages in logger then the rawMsg will be an array and you will have to cycle it...

**Comment by mvehar** [comment]
True, currently I was handling stringify/transformation in custom transports. I intended to use rawMsg, but embed JSON.stringify like at 
https://github.com/onubo/react-native-logs/blob/4ffa72226667ff25b643249e39c418e5a05255e6/src/index.ts#L315

Throws an error before transport is called. I would be good to provide custom stringify function in config and then we can use libs like https://www.npmjs.com/package/flatted. This was we also do not need to refactor the code, just replace the JSON.stringify with configurable function (that is by default JSON.stringify).

And thanks for heads up on rawMsg being an array.  👍

**Comment by alessandro-bottamedi** [comment]
@mvehar Allow custom stringify function in config its not a bad idea, I'll see if I can include it in the next release, thanks!
