### ISSUE TITLE
Expo file system not supported

### ISSUE THREAD

**Issue by oskfelin** [onubo/react-native-logs#29]
Current Expo/react-native-unimodules FileSystem implementation exports `EncodingType`. fileAsyncTransport is looking for `EncodingTypes` which results in throwing FileSystem not supported error

**Comment by alessandro-bottamedi** [comment]
i've removed EncodingType reference on fileAsyncTransport, can you test it?

**Comment by oskfelin** [comment]
Yes, it's fine now. I've already tested it myself before. Thanks!
