### ISSUE TITLE
Use console.* for consoleTransport

### ISSUE THREAD

**Issue by niklasu** [onubo/react-native-logs#30]
Right now, consoleTransport prints everything to console.log. In order to use LogBox from react-native, console.warn and console.error have to be used.

**Comment by alessandro-bottamedi** [comment]
Yes, you are right, the problem is that with this package you have the possibility to create custom log levels, error and warn levels do not necessarily exist. what are your suggestions?

**Comment by niklasu** [comment]
Thanks for the quick response 👍 

A suggestion how this can be implemented: When defining the log levels, also provide information, how the log levels map to console.log/debug/info/warn/error

`levels: {
    everything: {0, m => console.debug(m)},
    information: {1, m => console.info(m)},
    warnings: {0, m => console.warn(m)},
    severe: {0, m => console.error(m)},
  }`

**Comment by alessandro-bottamedi** [comment]
Implemented the new mapConsoleTransport in v 4.0.0 with the possibility to choose the preferred console method.
