### ISSUE TITLE
Bug? When the app is running longer than a day will the log file format still be correctly named?

### ISSUE THREAD

**Issue by pke** [onubo/react-native-logs#32]
I stumbled over the `fileName` config setting and it seems its only set during initialisation of the transport.

https://github.com/onubo/react-native-logs/blob/43b4ee5e195b6a1c22c76fcfd5fb3ca433c44710/src/transports/fileAsyncTransport.ts#L58

The means if the app stars one minute before midnight it would log to the wrong file from that moment on. No new file with the correct date will be create until app-restart.

Am I reading that correctly?

If so, an easy fix would be to have fileName be a function that is called on each append (could be a perf hit though).

**Comment by alessandro-bottamedi** [comment]
it is indeed as you wrote, if a user opens the app at 23:59 it will continue to use that file until it is restarted.

As you guessed, I didn't want to change the filename every time a log is made to avoid performance issues (although the fileTransport is already heavy so it might not affect performance too much).

Another alternative would be to add a method to dynamically change the transport options so that the user can change the file name when necessary, what do you think?

**Comment by pke** [comment]
On the desktop java frameworks usually optimise that using cron like syntax and tooling to roll over and package the old log files. It almost costs no perf of course (mostly I/O which runs in a second thread).

I thought about setting a timeout until midnight from current time but RN Android does not support long running timers (and will display a yellow box warning if a timeout is set longer than 30(?) mins.)

So how about a RollingFileAppender that checks the current dates day (date is fetched anyway to log it) and if it differs from the previous day it creates a new file and saves the new log entry and all following into the new file.

It could optionally gzip the previous day files.

I think we can pretty much learn from decades of high performance Java logging frameworks like log4j or even better slf4j.

**Comment by pke** [comment]
Is this fixed with the newest release? Is the filename function called on every log now as the readme example suggest?
If so you could close this issue ;)

**Comment by alessandro-bottamedi** [comment]
Fixed in v 5.0.0, you che use `date-today` as fileName to create a new file every day.
