### ISSUE TITLE
Enable all extensions by default

### ISSUE THREAD

**Issue by pke** [onubo/react-native-logs#33]
Common other logging libs like log4j or slf4j allow to crate namespaced loggers too. However, they always output those loggers by default.

It would greatly increase the workflow if one would not have to manually add each namespaced logger to the config.

Instead how about treating `enabledExtensions` as an include list only if it exists. Otherwise all extensions are enabled by default.

We could also think about something like the well known node package `debug` does by enabling fine grained sub-loggers via wildcards.

**Comment by alessandro-bottamedi** [comment]
Actually, your idea is not wrong, it makes much more sense to leave them enabled by default.
Using instead the `debug` way I think is complex especially if we want to maintain the current performance (to use the package well in production).

In the next version I will change enabledExtensions to an inclusive list. Thanks!

**Comment by pke** [comment]
@alessandro-bottamedi is this already in the current version?

**Comment by mat2718** [comment]
@pke i've been messing with for the last three days. you still have to enable the extension after you declare it.

**Comment by alessandro-bottamedi** [comment]
Sorry for the delay, I have been busy at work, I will update you in the next few days on the progress

**Comment by alessandro-bottamedi** [comment]
Since v 4.0.0 the extension system has been reversed, now if they are not set in the config, the logger will show them all.

**Comment by pke** [comment]
Hurray thanks for implementing that!
