### ISSUE TITLE
Failed to display  colour in console

### ISSUE THREAD

**Issue by briantical** [onubo/react-native-logs#37]
Hello, I am using the default example.  I have also reviewed some of the previous issues about displaying colour though I have failed to view the logs in the console in colour. I am also using typescript in my project.

Below is the implementation

```javascript
import { logger, consoleTransport } from "react-native-logs";

const defaultConfig = {
  severity: "debug",
  transport: consoleTransport,
  transportOptions: {
    color: "ansi", // custom option that color consoleTransport logs
  },
  levels: {
    debug: 0,
    info: 1,
    warn: 2,
    error: 3,
  },
  async: true,
  dateFormat: "time",
  printLevel: true,
  printDate: true,
  enabled: true,
};

var log = logger.createLogger(defaultConfig);
```

**Comment by alessandro-bottamedi** [comment]
Hi, which console do you use? for the chrome console try to change the `transportOptions.color` option:

`import { logger, consoleTransport } from "react-native-logs";

const defaultConfig = {
  transportOptions: {
    color: "web",
  },
};

var log = logger.createLogger(defaultConfig);`

**Comment by briantical** [comment]
I am using terminal

**Comment by alessandro-bottamedi** [comment]
I've tested with terminal (MacOS X Catalina) and I can see all colors without problems with the "ansi" option.
What kind of console do you have on terminal, ZSH?

**Comment by briantical** [comment]
Yes, i am using zsh

**Comment by alessandro-bottamedi** [comment]
Does anyone else experience the same problem?

**Comment by sunilloharshoreline1** [comment]
one thing I found is the key name is **colors** not the **color** . when I use ansi, i could see the color, web doesnt seem to work: 
transportOptions: {
    colors: "ansi"
  }

**Comment by alessandro-bottamedi** [comment]
Sorry, there was an error in the documentation, the right option is `colors`, set it to `web` for chrome and `ansi` for the terminal. Let me know if the problem persists and I will reopen the issue.
