### ISSUE TITLE
Filename/FilePath for rnFsFileAsync

### ISSUE THREAD

**Issue by creambyemute** [onubo/react-native-logs#4]
Hey there,

What would you think about slightly changing the rnFsFileAsync so that the filename/filepath is providable and not hardcoded?

Example usage: 
An App where you can login and want to log per user and not per app.

**Comment by alessandro-bottamedi** [comment]
Hi, i've just added the possibility to set transports options, as you can see in the docs now you can change the file name for the rnFsFileAsync (the transportOptions.loggerName property).
Abaout the path, in order to maintain the highest compatibility between android and ios for now I have left RNFS.DocumentDirectoryPath as I'm sure it works on all devices.
Did you have any advice to handle the path?

**Comment by creambyemute** [comment]
@alessandro-bottamedi I'd say make the path optional, if provided use that path, otherwise default to RNFS.DocumentDirectoryPath?

For the meantime I created my own customFsLog function which is called by my customLogger
```
private customLogger: transportFunctionType = async (msg: any, level: any) => {
        if (this.logLevel === "error") {
            if (this.isString(msg)) {
                Analytics.trackEvent(this.logTag, { msg: msg as string });
            } else if (this.isErrorObject(msg)) {
                Analytics.trackEvent(this.logTag, msg);
            } else if (this.isObject(msg)) {
                Analytics.trackEvent(this.logTag, msg);
            }
        }

        const logMessage = `${this.logTag}: ${JSON.stringify(msg)}`;
        this.fsLog(logMessage, level);

        if (__DEV__) {
            switch (this.logLevel) {
                case "info":
                    console.log(logMessage);
                    break;
                case "warn":
                case "error":
                    console.warn(logMessage);
                    break;
                default:
                    break;
            }
        }
    };
```

```
private fsLog: transportFunctionType = async (msg: any, level: any) => {
        const output = `${new Date().toLocaleString()} | ${level.text.toUpperCase()} | ${msg}\n`;
        const filePath = LowDBAdapter.path
            ? `${stores.rootStore.authStore.userDirectoryPath}rnfslogs.txt`
            : `${Constants.DatabaseDir}/rnfslogs.txt`;
        RNFS.appendFile(filePath, output, "utf8")
            .then(() => {})
            .catch((err: any) => {
                console.warn(err);
            });
    };
```

We're using DocumentDirectoryPath as well 
```
const DatabaseDir = Platform.select({
    ios: `${RNFS.DocumentDirectoryPath}`,
    android: `${RNFS.DocumentDirectoryPath}/../databases`
});

const DownloadDir = Platform.select({
    ios: `${RNFS.DocumentDirectoryPath}`,
    android: `${RNFS.DownloadDirectoryPath}`
});
```

I'm fine if you don't add the path as well as it's pretty easy/straightforward to setup a custom fs log as shown above.

**Comment by alessandro-bottamedi** [comment]
I added the option to set the path for rnFsFileAsync.
To set the path and filename after "RNFS.DocumentDirectoryPath" we can use the loggerName option.
if someone wants to change the path "RNFS.DocumentDirectoryPath", they can use the loggerPath option.
All TransportOptions are not required to keep the library easy to use.

**Comment by Vietvantue** [comment]
Two options to customize file and folder  are: **fileName** and **filePath** not **loggerPath**
