### ISSUE TITLE
`any` type for dynamic log methods

### ISSUE THREAD

**Issue by atheck** [onubo/react-native-logs#41]
Is it possible to not use `any` for dynamic log methods in class `logTyped`? Maybe these methods can be typed like this:

`(...args: unknown []) => void`

**Comment by alessandro-bottamedi** [comment]
Creating a standard type for the whole logger class without knowing the log level names first is complex.
However if you wanted to have a better typed log function you could create your own type and assign it to the logger object:

```javascript
type myLoggerType = {
  debug: (...args: unknown[]) => void;
  info: (...args: unknown[]) => void;
  warn: (...args: unknown[]) => void;
  error: (...args: unknown[]) => void;
};

const LOG = logger.createLogger(loggerConfig) as any as myLoggerType;
```

**Comment by atheck** [comment]
Thanks for your reply @alessandro-bottamedi. This is a good solution.
