### ISSUE TITLE
Sentrytransport  Error

### ISSUE THREAD

**Issue by bcteam2020** [onubo/react-native-logs#45]
Sentrytransport causing the below error 
**Error**
TaskQueue: Error with task : t.options.SENTRY.captureException is not a function. (In 't.options.SENTRY.captureException(t.msg)', 't.options.SENTRY.captureException' is undefined)

_App is getting crashed on open and above error is seen in Sentry._

**Configuration**
Expo managed workflow SDK 40
sentry expo package 4.0.1
react native loggers
**Config**
const config = {
    severity: DEV ? "debug":"error",
    transport: DEV ? consoleTransport : sentryTransport,
    transportOptions: {
      colors: "ansi", // custom option that color consoleTransport logs,
      SENTRY: Sentry
    },
    levels: {
      debug: 0,
      info: 1,
      warn: 2,
      error: 3,
    },
    async: true,
    dateFormat: "time",
    printLevel: true,
    printDate: true,
    enabled: true,
  };

**Comment by alessandro-bottamedi** [comment]
Sentry expo package seems to work a little differently, you can try this config:

```javascript
import * as Sentry from 'sentry-expo';

const config = {
  ...
  transportOptions: {
    SENTRY: Sentry.Native,
  },
};

var log = logger.createLogger(config);

log.error("Send this log to Sentry");
```

**Comment by bcteam2020** [comment]
Thanks, This is working
