### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by samaneh-kamalian** [onubo/react-native-logs#5]
Hi.thank you for your update.
there is problem in line 21 of /react-native-logs/dist/transports/rnFsFileAsync.js file
you must define let RNFS = require('react-native-fs'); and in line 32 you must remove let befor RNFS because you must define this in line befor line 21.

**Comment by jbreuer95** [comment]
https://github.com/onubo/react-native-logs/pull/6

**Comment by alessandro-bottamedi** [comment]
Hi, i've merged your pull thanks

**Comment by alessandro-bottamedi** [comment]
UPDATE: maybe the require RNFS line must be moved out of transport function? I think the code is cleaner... i make a commit now, can you try it?

**Comment by samaneh-kamalian** [comment]
Hi. I tested it and it worked well.thanks a lot
