### ISSUE TITLE
TransportOptions typings

### ISSUE THREAD

**Issue by pke** [onubo/react-native-logs#55]
Do you think it would be possible to improve the typings for configs so that by specifying which transport the config is the config for via template argument the transportOptions could be typed?

```ts
const config: configLoggerType<ConsoleTransportConfig> = {
}
```

**Comment by alessandro-bottamedi** [comment]
In v 5.0.0 I used this solution to type the levels, I believe they are the most important. I will also include typing for transportOptions soon.
