### ISSUE TITLE
monkey patch console?

### ISSUE THREAD

**Issue by pke** [onubo/react-native-logs#61]
Does anything speak against monkey-patching all console logging relevant methods by say, calling a `logger.install()` function?

This way one would not even have to import a logger into each module but it would simply work for all code using console.info etc?

**Comment by alessandro-bottamedi** [comment]
Indeed, this change could solve a large part of the current problems. however it is a little different from the original idea of ​​this package. let me think a bit.

**Comment by alessandro-bottamedi** [comment]
Added a patchConsole experimental method in v 5.0.0
