### ISSUE TITLE
No output produced after expo upgrade (to 45)

### ISSUE THREAD

**Issue by orome** [onubo/react-native-logs#63]
After expo upgrade (to 45) no logging appears using either console.log or a package like react-native-logs. Even explicitly enabling logging with
```
import { Logs } from 'expo'

Logs.enableExpoCliLogging()
```
produces no output.

**Comment by alessandro-bottamedi** [comment]
This issue its not related to react-native-logs, maybe it should be reported to expo, were you able to solve?
