### ISSUE TITLE
Hermes Engine `dateFormat` support

### ISSUE THREAD

**Issue by brandon93s** [onubo/react-native-logs#64]
### Overview
Hermes [currently supports](https://github.com/facebook/hermes/blob/main/doc/IntlAPIs.md) `toLocaleTimeString` and `toLocaleString` on Android **only**.  As a result, `time` is often the wrong timezone and the format of the date for `local` may be incorrect on iOS. 

https://github.com/onubo/react-native-logs/blob/9dfc362ec7a18885f9ad4844f69ac63e877086e2/src/index.ts#L295-L303

### Proposal
- Add alternative implementations of these formatters AND/OR
- Allow dateFormat to be a function so that the user can control formatting

```js
import {format} from 'date-fns'
import { logger, consoleTransport } from "react-native-logs";

const config = {
  dateFormat: (date) => format(date, 'h:mm a')
}

const log = logger.createLogger(config);
```

**Comment by alessandro-bottamedi** [comment]
Added in v 5.0.0
