### ISSUE TITLE
fileAsyncTransport() error

### ISSUE THREAD

**Issue by KrSerg** [onubo/react-native-logs#66]
Hi guys!

Noticed error in **_fileAsyncTransport_** function. If I won't use 'date-today' option in fileName - log file will be always named as 'log'.

Seems like you have an error in line 93:
`} else if (props?.options?.fileName) props.options.fileName;`

should be changed to:
`} else if (props?.options?.fileName) fileName  = props.options.fileName;`

**Comment by alessandro-bottamedi** [comment]
> Also, it would be great to have a custom file name with the `date-today` option for ex., 'my_app_v1.0_2022-07-04_qa.log' (where `2022-07-04` is `date-today`).

Good idea! fixed in v 5.0.1, now you can insert in the file name `{date-today}` and and it will be replaced with today's date, example: `fileName: 'my_app_v1.0_{date-today}_qa.log'`.

fileName fixed too, thanks @KrSerg.

**Comment by KrSerg** [comment]
@alessandro-bottamedi, thanks for such a quick fix! 👍

**Comment by dmytro-ivonin** [comment]
works as expected. thanks!
