### ISSUE TITLE
Suggestion: Multiple parameters on log()

### ISSUE THREAD

**Issue by lbanders** [onubo/react-native-logs#7]
Nice and simple framework...  have just added it and like it already :)

I'm though missing the option for console.log where you add multiple params so you could do like:
```log.error('An error occured', error);```

I believe that is more readable that doing:
```log.error(`An error occured ${error}`);```

Would that be a feature worth adding to your nice framework?

**Comment by alessandro-bottamedi** [comment]
Yes, I would like to implement this feature in the next version. But it cannot affect performance too much. I have to insert a cycle inside the log function...

**Comment by alessandro-bottamedi** [comment]
i'v added the multiple agruments ability to the log function in v 2.2.0, let me know if you have problem. thanks

**Comment by ajaysaini-sgvu** [comment]
I tried `logger.error('aa', 'b');` , it is displaying logs like below

```
[Wed May 13 2020 14:33:15.144]  LOG      %cWed May 13 14:32:32 2020 | ERROR | aa color: indianred;font-weight:bold;
[Wed May 13 2020 14:33:15.145]  LOG      %cWed May 13 14:32:32 2020 | ERROR | b color: indianred;font-weight:bold;
```

**Comment by alessandro-bottamedi** [comment]
see #10
