### ISSUE TITLE
Suggestion: Add create module logger

### ISSUE THREAD

**Issue by lbanders** [onubo/react-native-logs#8]
It would be nice to create a module logger, so the module name would be part of the log message.

I.e. you would have the base logger initialized with the configuration. From that one you would be able to create a logger for a given module. Something like ```const log = logger.loggerForModule('AuthModule`)``` and then you could do ```log.info('Authenticated user');``` which would give you:
```25/04/2020, 17:40:45 | INFO | AutheModule | Authenticated user```

**Comment by alessandro-bottamedi** [comment]
but maybe it's easier to create 2 loggers?
example: `var log = logger.createLogger();` and var `authLog = logger.createLogger();`
